added liveness and readiness probes to debug container partials template
linkerd/linkerd2 pull request #11308
Opened 2023-08-28 22:55 UTC by deusxanima

**Subject**

added liveness and readiness probes to debug container partials template

**Problem**

Some environments have security restrictions which require liveness and readiness probes in order to deploy any container in the cluster. Currently our debug container does not contain these, and there is no easy way for users to add the values into the container due to the way it's injected into the pod but not propagated to the deployment.

**Solution**

Added static liveness and readiness probes to debug container partials template which will always pass and evaluate to true.

Fixes #[[11307](https://github.com/linkerd/linkerd2/issues/11307)]

Alen Haric (deusxanima) aharic88@gmail.com

2023-08-31 22:32 UTC, olix0r requested changes

2023-08-31 22:32 UTC, olix0r commented on charts/linkerd-control-plane/values-ha.yaml
> +policyControllerResources: *controller_resources
These changes are duped from #11306. We'll want to either remove these from the branch or merge that PR first and then merge main into this branch...

2023-08-31 22:32 UTC, olix0r commented on charts/linkerd-control-plane/values.yaml
> +
```suggestion
```

2023-08-31 22:32 UTC, olix0r commented on charts/linkerd-control-plane/values-ha.yaml
> +
```suggestion
```

2023-10-24 19:51 UTC, alpeb approved these changes
I've replaced the commands with just `true`, fixed the golden files and the pod-with-debug.patch.json file :pray:

2023-10-24 22:33 UTC, adleong approved these changes

2023-10-25 09:20 UTC, mateiidavid approved these changes

2023-11-03 16:52 UTC, olix0r approved these changes

2023-11-03 16:55 UTC, merged