viz: add base path for web dashboard (#11851)
linkerd/linkerd2 pull request #11916
Opened 2024-01-11 10:00 UTC by WatcherWhale

Fixes #11851
Signed-off-by: Mathias Maes <mathias.maes@aloxy.io>

2024-01-31 14:59 UTC, WatcherWhale commented
> grafana also needs to consider switching uri's，Is it easy to modify? I can provide a test
> 
> #12015

This should already work, as I also changed the grafana reverse proxy in the go code

2024-04-25 18:57 UTC, kflynn requested changes
Hey, my apologies for the delay looking into this! I had to figure out some stuff on my end before I could look. 😐 

I left a couple of questions on the code, but the two biggest things I noticed when testing were

1. When I don't set `-base-path` I get 404s. 🙂 
2. I didn't actually manage to get Grafana hooked in – this might be my setup, though, how did you test this?

Thanks much for getting into this! and I apologize, again, for the delay. 😐

2024-04-25 18:57 UTC, kflynn commented on web/app/js/index.js
> +const pathArray = window.location.pathname.substring(pathPrefix.length).split('/');
It feels a little weird to me to not make sure that the path really does start with `pathPrefix` before doing this substring...

2024-04-25 18:57 UTC, kflynn commented on web/app/js/index.js
> +if (pathPrefix !== '' && pathArray[0] === '' && pathArray[1] === 'namespaces' && pathArray[2]) {
This doesn't seem quite right – you're making the entire check for a namespace in the path conditional on the path prefix being set?

2024-04-25 18:58 UTC, kflynn commented on viz/charts/linkerd-viz/README.md
> +| prometheus.resources | object | `{"cpu":{"limit":null,"request":null},"ephemeral-storage":{"limit":"","request":""},"memory":{"limit":null,"request":null}}` | Prometheus data volume size.  size: |
Ah yes, I feel like this should be a separate PR? or maybe this is just included by mistake.

2024-06-06 16:24 UTC, adleong commented
Closing as inactive.  Please feel free to reopen if you plan to continue work on this.

2024-06-06 16:24 UTC, closed without merging