Only set protocol hint when h2 upgrades are enabled
linkerd/linkerd2 pull request #6150
Opened 2021-05-20 18:26 UTC by kleimkuhler

While uncommon, if H2 upgrades are disabled it's possible for an opaque workload
to not have it's `hint.OpaqueTransport` field set in it's destination profile
response.

This changes the H2 upgrade enabled check to be specific for setting the
`hint.Protocol` while allowing `hint.OpaqueTransport` to be set independent of
that value.

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

2021-05-21 14:59 UTC, olix0r requested changes

2021-05-21 14:59 UTC, olix0r commented on controller/api/destination/endpoint_translator.go
> +			hint = &pb.ProtocolHint{
`hint` is only initialized in this conditional, but it's used below in a separation condition, which may segfault.

We need to initialize the `hint` outside of the `enableH2Upgrade`...

2021-05-24 16:45 UTC, mateiidavid submitted a review, later dismissed

2021-05-24 17:30 UTC, olix0r approved these changes

2021-05-24 19:00 UTC, adleong approved these changes

2021-05-24 20:15 UTC, merged