Add staticcheck to analysis tools
linkerd/linkerd2 pull request #7839
Opened 2022-02-08 00:57 UTC by kleimkuhler

When opening in a devcontainer, it is initially missing the `staticcheck` analysis tool.

Installation is from the [docs](https://staticcheck.io/docs/getting-started/#installation).

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

2022-02-08 03:14 UTC, olix0r commented
Not opposed to this, but I'm curious where you're hitting the need for it. Our golangci config currently disables this lint:
https://github.com/linkerd/linkerd2/blob/e03f6182f45baa922804e9d8dae42e8a5e8894e6/.golangci.yml#L43-L46

2022-02-08 15:48 UTC, kleimkuhler commented
When I open a devcontainer VS code always says that it's missing and that I should install it—similar to other analysis tools. Do you not get that when opening it?

2022-02-08 21:59 UTC, olix0r commented
I think you're seeing this because the default linter is _staticcheck_, but we rely on _golangci-lint_ (in CI). Using different linters is probably going to be painful, so the best change would probably be to update `devcontainer.json` to include the setting
```json
    "go.lintTool": "golangci-lint",
```

2022-02-08 22:49 UTC, adleong commented
So the devcontainer dockerfile pulls in golangci-lint@latest whereas the `bin/lint` script specifically is pinned to a specific version (1.43.0 currently).  We should eliminate one or the other or find a way to keep them in sync.

2022-02-08 23:06 UTC, olix0r commented
@adleong This issue existed before devcontainers came into the mix: VS Code (etc) wouldn't have any way to stay in sync with the version pinned in bin/lint.

I think it's fine to update/pin versions, but I don't think that's a problem introduced here.

2022-02-08 23:07 UTC, olix0r approved these changes
be sure to update the issue description, etc, before merging.

2022-02-08 23:07 UTC, olix0r commented on .devcontainer/devcontainer.json
> +    }
nit: can we move this up between `extensions` & `runArgs`?

2022-02-08 23:45 UTC, adleong commented
Ah, this issue didn't exist for me before because I didn't have any linting set up through VS Code and solely relied on bin/lint.  But if we're adding this to the devcontainer.json, I'll now have 2 potentially different versions in the mix.

It may be fine to simply remove bin/lint altogether.  The original goal of this script was to ensure uniformity between development environments and devcontainers mostly solve that problem (although floating on latest may introduce some inconsistency).

2022-02-09 00:10 UTC, kleimkuhler commented
`bin/lint` is used by CI though in the [static checks](https://github.com/linkerd/linkerd2/blob/f2fb35aa46b0126be5962dcf673b5690aae7710a/.github/workflows/static_checks.yml#L14-L24). Before removing the script we'd want to transition to the [golangci-lint action](https://github.com/golangci/golangci-lint-action).

I think this should be separately but I'm okay with removing `bin/lint` if we can.

2022-02-09 16:03 UTC, olix0r commented
Using the golangci-lint action seems fine/good, but it _still_ won't fix this problem. We'd need a way to detect when the devcontainer tooling diverges from the version in CI.

2022-02-14 17:59 UTC, adleong commented
Would it be possible to use our devcontainer image as the image used by the static checks action?  This should allow us to only have one version of golangci-lint.

2022-02-15 01:43 UTC, kleimkuhler commented
Ok `bin/lint` which is used locally and by static checks now parses `.devcontainer/Dockerfile` for the golangci-lint version which is currently 1.44.0.

2022-02-15 04:47 UTC, olix0r requested changes
I have some suggestions to keep this consistent with the other args in this file. Either this or we should change the others to be like this.

2022-02-15 04:47 UTC, olix0r commented on .devcontainer/Dockerfile
> +ARG GOLANGCI_LINT=1.44.0
```suggestion

FROM docker.io/golang:${GO_VERSION}-bullseye as go
ARG GOLANGCI_LINT_VERSION=v1.44.0
RUN for p in \
```

Let's try to make this consistent with the other app versions like `YQ_VERSION` and `CARGO_DENY_VERSION`. `YQ_VERSION` has a `v` prefix.

`RUST_TOOLCHAIN` should really be called `RUST_VERSION` but we can do that in a followup.

2022-02-15 04:47 UTC, olix0r commented on .devcontainer/Dockerfile
> +    github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT} \
```suggestion
    github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION} \
```

2022-02-15 04:47 UTC, olix0r commented on bin/lint
> +devcontainerdir=$( cd "$bindir"/../.devcontainer && pwd )
```suggestion
devcontainerdir=$( cd "$rootdir"/.devcontainer && pwd )
```

2022-02-15 04:47 UTC, olix0r commented on bin/lint
> +lintversion=$(sed -nE 's/^ARG GOLANGCI_LINT=([^ ]+)/\1/p' "$devcontainerdir"/Dockerfile)
```suggestion
lintversion=$(sed -nE 's/^ARG GOLANGCI_LINT_VERSION=(v[^ ]+)/\1/p' "$devcontainerdir"/Dockerfile)
if [ -z "$lintversion" ]; then
  echo "GOLANGCI_LINT_VERSION is not set in .devcontainer/Dockerfile" >&2
  exit 1
fi
```

2022-02-15 04:47 UTC, olix0r commented on bin/lint
> +  "$bindir"/scurl https://raw.githubusercontent.com/golangci/golangci-lint/v"$lintversion"/install.sh | sh -s -- -b . v"$lintversion"
```suggestion
  "$bindir"/scurl https://raw.githubusercontent.com/golangci/golangci-lint/"$lintversion"/install.sh | sh -s -- -b . "$lintversion"
```

2022-02-15 23:59 UTC, olix0r approved these changes

2022-02-16 00:08 UTC, adleong approved these changes
Looks like this will work and keep the versions in sync.  It still feels a bit more convoluted than necessary, but perhaps that could be address in a separate PR.  Ideally, we'd be able to get rid of the `bin/lint` script entirely and simply run the currently installed golang-ci-lint under the assumption that we are running within a reproducible environment (i.e. the devcontainer).

2022-02-16 00:08 UTC, merged