Allow AuthorizationPolicys to reference ServiceAccounts
linkerd/linkerd2 pull request #8709
Opened 2022-06-20 18:49 UTC by kleimkuhler

Closes #8565.

With this change, AuthorizationPolicys can now reference ServiceAccounts for their target authentications. This allows users to avoid the requirement of creating  a MeshTLSAuthentication resource that references a single ServiceAccount.

The policy admission controller only allows an AuthorizationPolicy to reference a single MeshTLSAuthentication _or_ a ServiceAccount; it cannot reference both. Additionally, if a ServiceAccount is reference it can onl be a single one — similar to MeshTLSAuthentications.

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

2022-06-20 20:48 UTC, adleong commented on policy-controller/k8s/index/src/index.rs
> +        for tgt in spec.authentications.iter() {
Can we combine these two loops and process both MeshTLS and ServiceAccount in the same loop?

```
for tgt in spec.authentications.iter() {
  match tgt {
    AuthenticationTarget::MeshTLS { ref namespace, ref name } => { ... },
    AuthenticationTarget::ServiceAccount { ref namespace, ref name } => { ... },
    AuthenticationTarget::Network { ref namespace, ref name } => { ... },
  }
}
```

2022-06-21 15:51 UTC, mateiidavid approved these changes
Looks good to me, modulo Alex's suggestion.

2022-06-23 17:13 UTC, adleong commented on policy-controller/k8s/index/src/index.rs
> +                        if let Some(authn) = ns.network.get(name).as_ref() {
I think this `.as_ref()` is unnecessary and results in a double ref

2022-06-23 17:14 UTC, adleong reviewed
Looks good.

TIOLI, but I find the continues nested inside if blocks make it a bit hard to reason about the control flow.  This is just personal style, but what do you think of a slightly more functional style?

e.g.

```
diff --git a/policy-controller/k8s/index/src/index.rs b/policy-controller/k8s/index/src/index.rs
index 7723d0a93..a924fe645 100644
--- a/policy-controller/k8s/index/src/index.rs
+++ b/policy-controller/k8s/index/src/index.rs
@@ -11,7 +11,7 @@ use crate::{
     pod, server, server_authorization, ClusterInfo,
 };
 use ahash::{AHashMap as HashMap, AHashSet as HashSet};
-use anyhow::{bail, Result};
+use anyhow::{anyhow, bail, Result};
 use linkerd_policy_controller_core::{
     AuthorizationRef, ClientAuthentication, ClientAuthorization, IdentityMatch, InboundServer,
     IpNet, Ipv4Net, Ipv6Net, NetworkMatch, ProxyProtocol, ServerRef,
@@ -1101,24 +1101,25 @@ impl PolicyIndex {
                 } => {
                     let namespace = namespace.as_deref().unwrap_or(&self.namespace);
                     tracing::trace!(ns = %namespace, %name, "Finding NetworkAuthentication");
-                    if let Some(ns) = all_authentications.by_ns.get(namespace) {
-                        if let Some(authn) = ns.network.get(name).as_ref() {
-                            tracing::trace!(ns = %namespace, %name, nets = ?authn.matches, "Found NetworkAuthentication");
-                            // There can only be a single required NetworkAuthentication. This is
-                            // enforced by the admission controller.
-                            if networks.is_some() {
-                                bail!("policy must not include multiple NetworkAuthentications");
-                            }
-                            let nets = authn.matches.clone();
-                            networks = Some(nets);
-                            continue;
-                        }
+                    let authn = all_authentications
+                        .by_ns
+                        .get(namespace)
+                        .and_then(|ns| ns.network.get(name))
+                        .ok_or_else(|| {
+                            anyhow!(
+                                "could not find NetworkAuthentication {} in namespace {}",
+                                name,
+                                namespace
+                            )
+                        })?;
+                    tracing::trace!(ns = %namespace, %name, nets = ?authn.matches, "Found NetworkAuthentication");
+                    // There can only be a single required NetworkAuthentication. This is
+                    // enforced by the admission controller.
+                    if networks.is_some() {
+                        bail!("policy must not include multiple NetworkAuthentications");
                     }
-                    bail!(
-                        "could not find NetworkAuthentication {} in namespace {}",
-                        name,
-                        namespace
-                    );
+                    let nets = authn.matches.clone();
+                    networks = Some(nets);
                 }
                 AuthenticationTarget::MeshTLS {
                     ref namespace,
@@ -1126,24 +1127,25 @@ impl PolicyIndex {
                 } => {
                     let namespace = namespace.as_deref().unwrap_or(&self.namespace);
                     tracing::trace!(ns = %namespace, %name, "Finding MeshTLSAuthentication");
-                    if let Some(ns) = all_authentications.by_ns.get(namespace) {
-                        if let Some(authn) = ns.meshtls.get(name) {
-                            tracing::trace!(ns = %namespace, %name, ids = ?authn.matches, "Found MeshTLSAuthentication");
-                            // There can only be a single required MeshTLSAuthentication. This is
-                            // enforced by the admission controller.
-                            if identities.is_some() {
-                                bail!("policy must not include multiple MeshTLSAuthentications");
-                            }
-                            let ids = authn.matches.clone();
-                            identities = Some(ids);
-                            continue;
-                        }
+                    let authn = all_authentications
+                        .by_ns
+                        .get(namespace)
+                        .and_then(|ns| ns.meshtls.get(name))
+                        .ok_or_else(|| {
+                            anyhow!(
+                                "could not find MeshTLSAuthentication {} in namespace {}",
+                                name,
+                                namespace
+                            )
+                        })?;
+                    tracing::trace!(ns = %namespace, %name, ids = ?authn.matches, "Found MeshTLSAuthentication");
+                    // There can only be a single required MeshTLSAuthentication. This is
+                    // enforced by the admission controller.
+                    if identities.is_some() {
+                        bail!("policy must not include multiple MeshTLSAuthentications");
                     }
-                    bail!(
-                        "could not find MeshTLSAuthentication {} in namespace {}",
-                        name,
-                        namespace
-                    );
+                    let ids = authn.matches.clone();
+                    identities = Some(ids);
                 }
                 AuthenticationTarget::ServiceAccount {
                     ref namespace,
```

2022-06-23 21:10 UTC, hawkw commented on policy-controller/k8s/index/src/index.rs
> +                            tracing::trace!(ns = %namespace, %name, nets = ?authn.matches, "Found NetworkAuthentication");
maybe the `namespace` and `name` fields should be added to a span?
```suggestion
                    let _span = tracing::trace_span!("network", ns = %namespace, %name).entered();
                    tracing::trace!("Finding NetworkAuthentication...");
                    if let Some(ns) = all_authentications.by_ns.get(namespace) {
                        if let Some(authn) = ns.network.get(name).as_ref() {
                            tracing::trace!(nets = ?authn.matches, "Found NetworkAuthentication");
```

2022-06-23 21:10 UTC, hawkw commented on policy-controller/k8s/index/src/index.rs
> +                            tracing::trace!(ns = %namespace, %name, ids = ?authn.matches, "Found MeshTLSAuthentication");
similarly, maybe
```suggestion
                    let namespace = namespace.as_deref().unwrap_or(&self.namespace);
                    let _span = tracing::trace_span!("mesh_tls", ns = %namespace, %name).entered();
                    tracing::trace!("Finding MeshTLSAuthentication...");
                    if let Some(ns) = all_authentications.by_ns.get(namespace) {
                        if let Some(authn) = ns.meshtls.get(name) {
                            tracing::trace!(ids = ?authn.matches, "Found MeshTLSAuthentication");
```

2022-06-24 20:46 UTC, olix0r requested changes
It's minor, but I'd prefer not to join the network & identity loops in this change -- the diff would be smaller without that change and I don't think it particularly helps readability.

2022-06-24 20:46 UTC, olix0r commented on policy-controller/src/admission.rs
> +
We can do this check before we do any of the net checks (i.e. move this up to 229).

2022-06-24 20:46 UTC, olix0r commented on policy-controller/src/admission.rs
> +            bail!("only MeshTLSAuthentication or ServiceAccount may be set");
This error message is not clear to me... It seems to insinuate that a NetworkAuthentication can't be set.

```suggestion
            bail!("a MeshTLSAuthentication and ServiceAccount may not be set together");
```

2022-06-27 15:45 UTC, kleimkuhler commented
Networks are processed in a separate loop and we ignore them in the match for identities (`_network => {}`).

2022-06-28 17:01 UTC, adleong commented on policy-controller/k8s/index/src/index.rs
> +                    continue;
I think this `continue` is redundant

2022-06-28 22:49 UTC, adleong approved these changes

2022-06-30 17:53 UTC, olix0r approved these changes

2022-07-01 19:45 UTC, merged