Update otel-collector image version and add port 4318 to otel-collector
linkerd/linkerd2 pull request #9379
Opened 2022-09-12 10:58 UTC by uralsemih

2022-09-23 21:45 UTC, adleong commented
Hi @uralsemih.  A few things that you'll need to do to fix up this PR:

* Add a `collector-otlp-http` Server resource to the `tracing-policy.yaml` template
* Run `go test ./... -update` to update the test fixtures
* Run `bin/helm-docs` to update the Helm docs
* Agree to the DCO as described in https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

2022-10-06 16:17 UTC, uralsemih commented
> Hi @uralsemih. A few things that you'll need to do to fix up this PR:
> 
> * Add a `collector-otlp-http` Server resource to the `tracing-policy.yaml` template
> * Run `go test ./... -update` to update the test fixtures
> * Run `bin/helm-docs` to update the Helm docs
> * Agree to the DCO as described in https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

@adleong 
Do you want me to create another PR for this ?

2022-10-06 22:10 UTC, adleong commented
You should be able to push more commits to your branch on your fork to implement the necessary changes.

2022-10-15 07:57 UTC, uralsemih commented
I agree to the DCO for all the commits in this PR.

2022-10-15 07:58 UTC, uralsemih commented
@adleong Please let me know if there is any missing thing

2022-10-20 14:36 UTC, alpeb requested changes

2022-10-20 14:36 UTC, alpeb commented on jaeger/charts/linkerd-jaeger/templates/tracing-policy.yaml
> +  proxyProtocol: htto
```suggestion
  proxyProtocol: HTTP/1
```

2022-10-20 15:16 UTC, alpeb commented
Fixes #9366

2022-11-03 14:56 UTC, alpeb commented
@uralsemih can you please take care of the typo I flagged above?

2022-11-17 21:19 UTC, kleimkuhler commented
Checking in @uralsemih do you need anything in order to wrap this up?

2022-11-18 11:01 UTC, uralsemih commented
> @uralsemih can you please take care of the typo I flagged above?

Sorry for the late reply. Here I did 10d1cece4291aeb8aca2344656ae6459ae0cd9f2

2022-11-23 18:48 UTC, adleong approved these changes

2022-11-24 20:37 UTC, alpeb approved these changes
LGTM :+1:

2022-11-24 20:41 UTC, merged